#! /usr/bin/python3
from PySide2.QtWidgets import QApplication
from PySide2.QtQuick import QQuickView
from PySide2.QtCore import QUrl, QObject, Slot, Signal,Property
import os
import subprocess
import sys
import shutil
from pathlib import Path

class Tunnel(QObject):
	
	def __init__(self):

		QObject.__init__(self)
		self.clearCache()

	#def __init

	def clearCache(self):

		clear=False
		userHome=Path.home()
		versionFile=userHome /".config/lliurex-guard-natfree.conf"
		cachePath1=userHome / ".cache/lliurex-guard-natfree"
		cachePath2=userHome / ".cache/lliurex-guard-natfree-gui"
		installedVersion=self.getPackageVersion()

		if not versionFile.exists():
			versionFile.write_text(installedVersion)
			clear=True

		else:
			fileVersion=versionFile.read_text().strip()

			if fileVersion!=installedVersion:
				versionFile.write_text(installedVersion)
				clear=True
		
		if clear:
			if cachePath1.exists():
				shutil.rmtree(cachePath1)
			if cachePath2.exists():
				shutil.rmtree(cachePath2)

	#def clearCache

	def getPackageVersion(self):

		packageVersionFile=Path("/var/lib/lliurex-guard-natfree/version")
		pkgVersion=""

		if packageVersionFile.exists():
			pkgVersion=packageVersionFile.read_text().strip()

		return pkgVersion

	#def getPackageVersion
		
	@Slot(str)
	def on_ticket(self, ticket):
	
		tk=ticket.replace(' ','##U+0020##')
		cmd=["python3","/usr/sbin/lliurex-guard-natfree-gui",tk]
		subprocess.Popen(cmd,)
		QApplication.quit()
	
	#def on_ticket
	

#class Tunnel

app = QApplication([])
tunnel = Tunnel()
view = QQuickView()
view.rootContext().setContextProperty("tunnel", tunnel)
url = QUrl("/usr/lib/python3/dist-packages/lliurexguardnatfree/rsrc/login.qml")
view.setSource(url)
view.show()
ret=app.exec_()
del view
del app
sys.exit(ret)
