#!/bin/sh

case "$1" in
	configure)
	                zero-center set-configured lliurex-guard-installer || true
	                if dpkg --compare-versions "$2" lt 5.7; then
				/usr/sbin/lliurex-guard-fix-blacklist
				if [ -e /etc/dnsmasq.d/lliurex-guard.conf ]; then
					sed -i -e "s/addn-hosts/conf-dir/g" /etc/dnsmasq.d/lliurex-guard.conf
				fi
	                fi
		;;
	*)
		echo "Unknow action"
		;;
esac

#DEBHELPER#
