#!/usr/bin/env python3
import os
from os import write
import re
from pathlib import Path
import tempfile
import shutil

def write_line(l, fd):
    fd.write(l + "\n" )

def process_folder(folder):

    sanitize_items=["--",".-","-.","0.",".0",'0-',"-0",]
    
    if not os.path.exists(folder):
        return False
    for blacklist_file in folder.iterdir():
        fd_temp = tempfile.NamedTemporaryFile(mode="w",encoding="utf-8")
        with blacklist_file.open("r",encoding="utf-8") as fd:
            while line := fd.readline():
                reject_line=False
                line = line.strip()
                if line.startswith("#"):
                    write_line(line,fd_temp.file)
                    continue
                else:
                    for item in sanitize_items:
                        if item in line:
                            reject_line=True
                            break
                    if not reject_line:
                        if len(line.split("-"))>2:
                            pass
                        else:
                            write_line(line,fd_temp.file)

        fd_temp.file.close()
        shutil.copy(fd_temp.name, str(blacklist_file))
        fd_temp.close()

def main():
    blacklist_path = Path("/etc/lliurex-guard/blacklist")
    blacklist_path_d = Path("/etc/lliurex-guard/blacklist.d")
    process_folder(blacklist_path)
    process_folder(blacklist_path_d)


if __name__ == "__main__":
    main()

        
