#!/usr/bin/env python3
from PySide6.QtWidgets import QApplication
from PySide6.QtCore import QUrl
from PySide6.QtGui import QIcon
from PySide6.QtQml import QQmlApplicationEngine

import sys
from lliurexguard.Core import Core

c=Core.get_core()

app=QApplication()
engine = QQmlApplicationEngine()
engine.clearComponentCache()
context=engine.rootContext()
mainStackBridge=c.mainStack
guardOptionsStackBridge=c.guardOptionsStack
listStackBridge=c.listStack
context.setContextProperty("mainStackBridge", mainStackBridge)
context.setContextProperty("guardOptionsStackBridge", guardOptionsStackBridge)
context.setContextProperty("listStackBridge", listStackBridge)

url = QUrl("/usr/lib/python3.12/dist-packages/lliurexguard/rsrc/lliurex-guard.qml")

engine.load(url)
if not engine.rootObjects():
	sys.exit(-1)

engine.quit.connect(QApplication.quit)
app.setWindowIcon(QIcon("/usr/share/icons/hicolor/scalable/apps/lliurex-guard.svg"));
ret=app.exec()
del engine
del app
sys.exit(ret)



